"""add_comprehensive_profile_fields

Revision ID: 5deb3aa14285
Revises: f87257fe1fb0
Create Date: 2025-07-28 17:15:19.365123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5deb3aa14285'
down_revision: Union[str, Sequence[str], None] = 'f87257fe1fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('timeline', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('education_level', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('work_style', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('funding_preference', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('location_preference', sa.String(), nullable=True))
    op.alter_column('user_profiles', 'experience_years',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'experience_years',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('user_profiles', 'location_preference')
    op.drop_column('user_profiles', 'funding_preference')
    op.drop_column('user_profiles', 'work_style')
    op.drop_column('user_profiles', 'education_level')
    op.drop_column('user_profiles', 'timeline')
    # ### end Alembic commands ###
